In [1]:
import importlib
import quickgsim as gsim

In [2]:
importlib.reload(gsim)

<module 'quickgsim' from '/Users/andreas/OneDrive - University of Edinburgh/code_projects/quickgsim/src/quickgsim/__init__.py'>

In [3]:
g = gsim.Genome(seed=None)

In [4]:
gsim.read_snps(g,"../examples/c28.csv",cm_col=3)

will now add chromsome 28


In [5]:
sum(g.chroms['28'].cm_pos)

1.0000000000000002

In [6]:
g.chroms['28'].p_to_cm()

In [7]:
max(g.chroms['28'].cm_pos)

46.6

In [8]:
g.chroms['28'].morgans

0.466

In [12]:
def get_elem(array,pos,typos=str,def_val=None,verbose=False):
    """Wraps the try/except functionality to emaulate the <dict>.get() behaviour"""
    if pos is not None:
        try:
            return typos(array[pos])
        except ValueError:
            print(array)
            if verbose:
                print(f"**WARNING: unable to convert value in position {pos} to type {typos}")
        except IndexError:
            print(array)
            if verbose:
                print(f"**WARNING: unable to retrieve value in position {pos} from array {array}")
    return def_val

In [5]:
f = open("ADAPTmap_genotypeTOP_20160222_full/ADAPTmap_genotypeTOP_20160222_full.bim")
next(f)

'0\tsnp10134-scaffold1361-15149\t0\t0\tA\tG\n'

In [6]:
tmp = next(f).strip().split(None)
print(tmp)

['0', 'snp10135-scaffold1361-44576', '0', '0', 'A', 'G']


In [7]:
snpid,chrom,cm_pos = get_elem(tmp,1), get_elem(tmp,0,verbose=True), get_elem(tmp,None,typos=float)

In [13]:
get_elem(tmp,0)

'0'

In [ ]:
with open(inFile) as fin:
        if header:
            next(fin)

        for row in fin:
            tmp = row.strip().split(sep)
            snpid,chrom,cm_pos = get_elem(tmp,id_col), get_elem(tmp,chr_col,verbose=True), get_elem(tmp,cm_col,typos=float)
            if chrom:
                genome.add_variant(chrom,cm_pos)
            
        for chrom in genome.chroms:
            genome.chroms[chrom].finalise_configuration()

In [26]:
def cm_to_p(cm,d):
    ##check https://numpy.org/doc/stable/reference/generated/numpy.diff.html
    return np.diff(cm,prepend=0)/d

def p_to_cm(cm,d):
    cm = cm*d
    return np.cum(c)
    print(tmp)
    cm[0] = tmp[0]
    cm[1:] = np.cumsum(tmp[1:])
    return cm

In [16]:
import numpy as np
a = np.array([2,3,6,29,50])
d = max(a)

In [22]:
cm_to_p(a,d)

array([0.04, 0.02, 0.06, 0.46, 0.42])

In [27]:
p_to_cm(np.array([0.04, 0.02, 0.06, 0.46, 0.42]),d)

[ 2.  1.  3. 23. 21.]


array([ 2.,  1.,  4., 27., 48.])

In [ ]:
from collections import Counter

m = [1,2,3,4,5]
p = [0.04,0.02,0.06,0.46,0.42]

draw = lambda x,p=None : g.rs.choice(x,1,p=p)[0]
uni = Counter([draw(m) for i in range(10000)])
wei = Counter([draw(m,p) for i in range(10000)])

uni
#Out[54]: Counter({3: 2004, 1: 1966, 2: 1983, 5: 2016, 4: 2031})

wei
#Out[55]: Counter({4: 4579, 5: 4139, 2: 214, 3: 648, 1: 420})

## validate
get_obs_p = lambda x: [x[k]/sum(x.values()) for k in sorted(x.keys())]

get_obs_p(wei)
#Out[59]: [0.042, 0.0214, 0.0648, 0.4579, 0.4139]

get_obs_p(uni)
#Out[61]: [0.1966, 0.1983, 0.2004, 0.2031, 0.2016]


In [14]:
from collections import UserDict

In [26]:
class Genotype(UserDict):
    
    def __init__(self,chroms):
        self.data = {}
        for c in chroms:
            self.data[c] = {0:[],1:[]}
    
    def iterate_chroms(self,specific_chroms=[]):
        chroms = self.data.keys()
        if specific_chroms:
            chroms = (c for c in specific_chroms if self.data.get(c,None))
        return chroms
    
    

In [29]:
g1 = Genotype([1,2])
for c in g1.iterate_chroms([1,3]):
    print(g1[c])

{0: [], 1: []}


In [25]:
g1[1]

{0: [], 1: []}

In [57]:
from  dataclasses import dataclass
from typing import Optional

In [74]:
@dataclass
class A:
    n: str
    t: int or None
    
    def __repr__(self):
        return f"{self.n} -> {self.t}"

In [77]:
a1 = A("Assa",None)

In [78]:
a1

Assa -> None